config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :candidates do
    member do 
      # put :vote, to: 'candidate#vote'
      put :vote   #put /candidate/2/vote
    end
  end

  get '/index', to: 'candidates#index'

  root 'candidates#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
    validates(:name, { presence: true})
    validates :age, numericality: { greater_than_or_equal_to: 40}
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :find_candidate, only: [:show, :edit, :update, :destroy, :vote] #還有 except 方法
  # 用 before_action 的話，在:show, :edit, :udate, :destroy就都可以不用寫 find_candidate



  def index
    @candidates = Candidate.all.order(vote: :desc)
  end

  def show
    # @candidate = Candidate.new(:id)
    # @candidate = Candidate.find_by(id: params[:id])
    # find_candidate
  end
  
  def edit
    # @candidate = Candidate.find_by(id: params[:id])
    # find_candidate
  end

  def new
    @candidate = Candidate.new
  end

  def update
    # @candidate = Candidate.find_by(id: params[:id])
    # find_candidate
    # clean_params = params.require(:candidate).permit(:name, :age, :policy, :party)

    if @candidate.update(candidate_params)
      # flash[:notice] = "更新成功!!"
      redirect_to '/candidates', notice: "更新成功！"
    else
      render :edit
    end
  end 
  
  def destroy
    # @candidate = Candidate.find_by(id: params[:id])
    # find_candidate
    @candidate.destroy
    # flash[:notice] = "資料刪除成功"
    # redirect_to root_path
    redirect_to root_path, notice: "資料刪除成功！"

  end

  def vote
    v = @candidate.vote || 0
    # @candidate.update(vote:v + 1)
    # VoteLog.new(candidate_id: @candidate.id, ip: remote_ip)
    VoteLog.create(candidate_id: @candidate.id, ip_address:request.remote_ip)
    redirect_to root_path, notice: "投票成功！"
  end

  def create

    #在終端機 打 rails console 可查看傳送到資料庫的資料 ex: Candidate.first
    #在終端機 打 rails c --sandbox 可以測試改變, 但是結束後會回復初始狀態

    # render html: "123"
    # render html: params
    # clean_params 叫做 strong parameter
    # clean_params = params.require(:candidate).permit(:name, :age, :policy, :party)
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      # flash[:notice] = "新增成功！"
      # redirect_to root_path
      
      redirect_to root_path, notice: "新增成功！"
    else
      # render html: 'UCCU'
      # redirect_to new_candidate_path

      render :new
    end

  end
  private
  def find_candidate
    @candidate = Candidate.find_by(id: params[:id])
  end
  def candidate_params
    params.require(:candidate).permit(:name, :degree, :age, :policy, :party)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/_form.html.erb
<% if @candidate.errors.any? %>
  <ul>
  <% @candidate.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul><p></p>
<% end %>

<%= form_for(@candidate) do |form| %>
  <div class="box">
    <div class="candidate_field">
      <%= form.label :name, '姓名' %>
      <%= form.text_field :name %>
    </div>
    <div class="candidate_field">
        <%= form.label :degree, '學歷' %>
        <%= form.text_field :degree %>
    </div>
<%= %>
    <div class="candidate_field">
      <%= form.label :party, '黨派' %>
      <%= form.text_field :party %>
    </div>

    <div class="candidate_field">
      <%= form.label :age, '年紀' %>
      <%= form.text_field :age %>
    </div>

    <div class="candidate_field">
      <%= form.label :policy, '政策' %>
      <%= form.text_area :policy %>
    </div>
    <%= form.submit class: 'btn btn-success btn-lg' %>
  </div>
<% end %>p

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render 'form' %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<!-- timeframe: 11:20 -->
<ul>
  <% @candidates.each do |candidate| %>
    <li>
      <%= link_to "投票給這位！", vote_candidate_path(candidate.id), class: 'btn bg-xs btn-warning', method: "put" %>
      <%= candidate.vote || 0 %>
      <%= link_to candidate.name, candidate_path(candidate.id) %>
      <%= link_to "編輯", edit_candidate_path(candidate.id), class: 'btn bg-xs btn-success' %>
      <%= link_to '刪除', candidate_path(candidate.id), class: 'btn bg-xs btn-danger', method: 'delete', data: { confirm: '確定嗎?!'}%>
    </li>
  <% end %>
</ul>


<%= link_to '新增候選人', new_candidate_path, class: 'btn btn-success btn-lg'%>

<!-- 下面兩行效果都一樣
<%#= link_to candidate.name, candidate_path(candidate.id) %>
<%#= link_to candidate.name, candidate %> -->

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render 'form' , candidate: @candidate %>

app/views/candidates/show.html.erb
<% if @candidate  %>
  <h1><%= @candidate.name %></h1>

  <ul>
    <li>年紀:<%= @candidate.age %></li>
    <li>學歷:<%= @candidate.degree %></li>
    <li>黨派:<%= @candidate.party %></li>
    <li>政見:<%= @candidate.policy %></li>
    <li>票數:<%= @candidate.vote %></li>
  </ul>
<% else %>
  <h1>沒有這個人</h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ivoting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/frontend/navbar' %>
    <%= flash[:notice] %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/frontend/_navbar.html.erb
<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>